version: "3"

services:
  api:
    build:
      context: .
    command: npm run dev
    ports: 
      - 9898:9898
    depends_on:
      - mongo
    volumes:
      - .:/code
  mongo:
    image: mongo:4-bionic
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
